### ISSUE TITLE
Tests don't build with openssl 1.1.0g

### ISSUE THREAD

**Issue by tuxmaster** [signalapp/libsignal-protocol-c#101]
Testes with: 2.3.1
Because of the amount of build errors, I only append the log file.

[build.log](https://github.com/signalapp/libsignal-protocol-c/files/1754766/build.log)

**Comment by tuxmaster** [comment]
OpenSSL 1.0.2m will work.

**Comment by dkonigsberg** [comment]
There is no 2.3.1 version tag. Were you testing against latest master, 2.3.0, or something else?
OpenSSL 1.1 support was added in commits v2.3.0-18-g0dbc7bd and v2.3.0-19-gd5e50f5.

**Comment by dkonigsberg** [comment]
Okay, I see you're probably trying to build the v2.3.1 tarball, which was generated a few commits before OpenSSL 1.1 support was added.

The library is normally used by tracking master, and statically linking into a larger application. As such, not much attention has been given to numbered versions, so its long overdue for another round of tagging.
