### ISSUE TITLE
Feature req: group rules

### ISSUE THREAD

**Issue by mm-s** [signalapp/libsignal-protocol-c#113]
This is not actually a bug report, It is a feature request.
I had the necessity to create a group, add members, write a permanent header in the channel containing rules, and the app asking for acceptance of the rules before new members can write their first message.
So I thought this could be a feature request.
Thank you
Marcos

I have:
- [ ] searched open and closed issues for duplicates

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by dkonigsberg** [comment]
This sounds like an application-level feature request, and not something appropriate for this library. If that's true, please re-submit this issue elsewhere.
