### ISSUE TITLE
2 things: Q/issue and BIG suggestion

### ISSUE THREAD

**Issue by nk8020** [signalapp/libsignal-protocol-c#146]
### Bug description
Desktop version does not play SMS on Desktop after linking devices, nor does it play sound as checked in 'preferences'

### Steps to reproduce

-Link Desktop to Android device
-Send an SMS message
-Watch as it does nothing on the desktop, not even showing SMS

### Device info

Xiaomi Redme Note 7
Android ver. 10
Signal ver. 5.0.8

### PC info

Windows 10 x64 (all updated)

**Comment by dkonigsberg** [comment]
This is the project for the E2E encryption library used by Signal, not the app itself.
