### ISSUE TITLE
Intermittent failing encryption/decryption

### ISSUE THREAD

**Issue by timt** [signalapp/libsignal-protocol-c#87]
I have a java client producing SignalMessage and sending them to an iOS client.

I have a strange situation where after having successfully processed/decrypted the PreSignalMessage, calling encryptData in the iOS app to create a response message fails with a 'Code 0 - Unknown error'

After some investigation, I found that if simply repeating the call to SignalSessionCipher.encryptData step recursively it will eventually succeed.

Sometimes it works on the first invocation but other times it can take  10-15 attempts.

(With java to java clients I do not see this issue)

Can anyone shed some light on this or point me in the direction of how to isolate the problem?

**Comment by dkonigsberg** [comment]
Closing, due to no updates and because "Code 0 - Unknown error" is not an error message this library will generate.
